"""2_add Department

Revision ID: 43245220b802
Revises: 30398e63c795
Create Date: 2024-10-23 01:12:58.665965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43245220b802'
down_revision = '30398e63c795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
